### ISSUE TITLE
Cats have the opportunity to frantically switch between their original sitting position and cat bread after going to bed on their own

### ISSUE THREAD

**Issue by AWAKEN-1** [Khajiitos/CatLoaf#2]
like this

https://github.com/Khajiitos/CatLoaf/assets/77484596/a2324907-4ad0-41b5-83cb-d4a25c59abc0

**Comment by Khajiitos** [comment]
Do you know which version of the mod was used here? This should technically be fixed in the latest version

**Comment by AWAKEN-1** [comment]
My bad, it looks like it's been fixed in the latest version ...
