### ISSUE TITLE
My favorite mod (this one) won't load

### ISSUE THREAD

**Issue by dima-dencep** [Khajiitos/CatLoaf#4]
![image](https://github.com/Khajiitos/CatLoaf/assets/66722732/ac3f33dd-e5d2-4e9a-b028-fda1b21edf4c)

**Comment by Khajiitos** [comment]
Can you show me the log? Maybe it will be more descriptive. Maybe NeoForge had changed something that it doesn't want to load mods built for an older version for it.

**Comment by dima-dencep** [comment]
Don't worry, I'm going to create a PR that will fix this


> Maybe NeoForge had changed something that it doesn't want to load mods built for an older version for it.

https://neoforged.net/news/20.5release/#:~:text=The%20neoforge.mods.toml%20File

**Comment by dima-dencep** [comment]
😼
